# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E8EAE9
background         #111212
cursor             #A29D94

active_tab_foreground     #111212
active_tab_background     #E8EAE9
inactive_tab_foreground   #E8EAE9
inactive_tab_background   #111212

active_border_color   #E8EAE9
inactive_border_color #111212
bell_border_color     #121411

color0      #393A3A
color1		#121411
color2		#453C2E
color3		#503E31
color4		#725E48
color5		#806950
color6		#8E9291
color7		#D6D8D8
color8		#959797
color9		#181B17
color10		#5C503E
color11		#6B5241
color12		#977D60
color13		#AB8C6B
color14		#BDC2C1
color15		#D6D8D8
