-- Generated by nwg-displays on 2026-07-16 at 23:32:25. Do not edit manually.

-- hl.monitor({
--   output = "DP-2",
--   mode = "1920x1080@60.0",
--   position = "963x0",
--   scale = 1.0,
-- })
-- hl.monitor({
--   output = "HDMI-A-1",
--   mode = "1920x1080@144.0",
--   position = "0x0",
--   scale = 1.33,
--   transform = 1,
-- })

-- TV
hl.monitor({
  output = "HDMI-A-1",
  mode = "3840x2160@60.0",
  position = "0x0",
  scale = 2,
})
