# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #D8D8D9
background         #161616
cursor             #979798

active_tab_foreground     #161616
active_tab_background     #D8D8D9
inactive_tab_foreground   #D8D8D9
inactive_tab_background   #161616

active_border_color   #D8D8D9
inactive_border_color #161616
bell_border_color     #161616

color0      #3D3D3D
color1		#161616
color2		#404142
color3		#444445
color4		#73353A
color5		#6B6B6E
color6		#6B6B6E
color7		#BEBFC0
color8		#858586
color9		#1E1E1E
color10		#565658
color11		#5A5A5C
color12		#99474D
color13		#8F8F92
color14		#8F8F92
color15		#BEBFC0
