[Icon Theme]
Name=BeautyLine
Inherits=breeze,Adwaita,ubuntu-mono,yaru,Mint-X,elementary,hicolor


# Directory list
Directories=actions/scalable,places/16,places/48,apps/scalable,devices/scalable,mimetypes/scalable
Example=folder
DisplayDepth=32

FollowsColorScheme=true

DesktopDefault=48
DesktopSizes=16,22,32,48,64,128,256
ToolbarDefault=22
ToolbarSizes=16,22,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,32,48
SmallDefault=16
SmallSizes=16,22,32,48
PanelDefault=48
PanelSizes=16,22,32,48,64,128,256
DialogDefault=32
DialogSizes=16,22,32,48,64,128,256

KDE-Extensions=.svg

[devices/scalable]
Context=Devices
Size=64
MinSize=8
MaxSize=192
Type=Scalable

[actions/scalable]
Context=Actions
Size=22
MinSize=8
MaxSize=192
Type=Scalable

[actions/scalable]
Context=Status
Size=22
MinSize=8
MaxSize=192
Type=Scalable

[apps/scalable]
Size=96
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable

[mimetypes/scalable]
Context=MimeTypes
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[places/16]
Size=16
Context=Places
MinSize=8
MaxSize=48
Type=Scalable


[places/48]
Size=48
Context=Places
MinSize=48
MaxSize=512
Type=Scalable

