alias lg="lazygit"
alias gadd="forgit::add"
alias gadd-all="forgit::add ."
alias glog="forgit::log"
alias gdiff="forgit::diff"
alias greset-ahead="forgit::reset::ahead"
alias gignore="forgit::ignore"
alias gcheckout-file="forgit::checkout::file"
alias gcheckout-tag="forgit::checkout::tag"
alias gcheckout-commit="forgit::checkout::commit"
alias grevert-commit="forgit::revert::commit"
alias gcheckout-branch="forgit::checkout::branch"
alias gbranch-delete="forgit::branch::delete"
alias gclean="forgit::clean"
alias gshow-stash="forgit::stash::show"
alias gcherry-pick="forgit::cherry::pick"
alias grebase="forgit::rebase"
alias gblame="forgit::blame"
alias gfixup="forgit::fixup"

alias gstatus="git status"
alias gclone="git clone --depth 1"
alias gfetch="git fetch"
alias gbranch="git branch"
alias gcommit="git commit -m"
alias ginit="git init"
alias gpull="git pull origin"
alias gpush="git push origin"
alias grebase-abort="git rebase --abort"
alias grebase-continue="git rebase --continue"

## Bare git repo alias for dotfiles
alias gloorifiles="/usr/bin/git --git-dir=$HOME/Gl00riFiles/ --work-tree=$HOME"
