#!/usr/bin/env bash

# reset XDPH for screenshare
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-gnome
killall xdg-desktop-portal-kde
killall xdg-desktop-portal-lxqt
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
sleep 1
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

# https://wiki.hyprland.org/FAQ/#some-of-my-apps-take-a-really-long-time-to-open
# https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP & # for XDPH
dbus-update-activation-environment --systemd --all &                               # for XDPH
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &          # for XDPH

# Policy Authentication Agent (Gnome | KDE)
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/polkit-kde-authentication-agent-1 & # authentication dialogue for GUI apps

# stores password & encryption keys
# eval "$(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"
# export "$(gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)"

# export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/gcr/ssh

# gsettings
# gsettings set org.gnome.desktop.interface gtk-theme 'Tokyonight-Dark-BL-LB'
# gsettings set org.gnome.desktop.interface font-name 'CaskaydiaCove Nerd Font 9'
# gsettings set org.gnome.desktop.interface icon-theme 'Tokyonight-Moon'
# gsettings set org.gnome.desktop.interface cursor-theme 'Sweet-cursors'

#####################################
#              Apss                 #
#####################################

# wallpaper
wpaperd &

# OSD window for common actions like volume and capslock
# (https://github.com/ErikReider/SwayOSD)
exec swayosd-server &

# notification daemon
# dunst &
swaync &

# automatic mount storage-devices
udiskie &

# waybar
~/.config/hypr/scripts/launch_waybar.sh &
# gBar bar 0 & # main monitor
gBar bar 1 & # secondary monitor

# battery notification
~/.config/hypr/scripts/batterynotify.sh &

# eww
eww daemon

# applets
# ~/.config/hypr/scripts/appindicator.py &
blueman-applet &
nm-applet --indicator &

# cursor & touchpad gestures
hyprctl setcursor Sweet-cursors 24 &
libinput-gestures-setup start &

# clipboard
wl-paste --type text --watch cliphist store &  # store text data
wl-paste --type image --watch cliphist store & # store image data

# idle
swayidle -w timeout 600 "swaylock" before-sleep "swaylock" & # lock screen after 10 min of idle
swayidle -w timeout 1200 "systemctl hibernate" &             # hibernate after 20 mins of idle
